import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        // Optional: Ensure Tailwind classes apply correctly (especially with Tailwind v4+)
        // cssLayerName: 'clerk',

        // Define your black and white color palette
        variables: {
          colorPrimary: 'black',       // Primary actions (buttons)
          colorText: '#333333',        // Dark gray for general text
          colorInputText: '#000000',    // Black for input text
          colorBackground: '#FFFFFF',   // Pure white for overall background
          colorInputBackground: '#FFFFFF', // White for input fields
          colorNeutral: '#CCCCCC',     // Light gray for borders, dividers, etc.
          colorDanger: '#DC2626',      // A standard red for errors (still good to have)
          colorSuccess: '#22C55E',     // A standard green for success
          colorWarning: '#FACC15',     // A standard yellow for warning
          // You can also adjust border radius and fonts for a monochrome look
          borderRadius: '0.25rem',     // Slightly rounded, or 0 for sharp
          // fontFamily: 'sans-serif', // Use a clean, simple font
        },
        elements: {
          // General card styling
          card: 'shadow-none border border-gray-300 rounded-sm', // Minimal shadow, light border

          // Primary button styles (e.g., "Sign Up")
          formButtonPrimary: 'bg-black text-white hover:bg-gray-800 focus:ring-2 focus:ring-gray-500 focus:ring-offset-2',

          // Secondary button styles (e.g., social login buttons)
          socialButtonsBlockButton: 'bg-white text-black border border-gray-400 hover:bg-gray-100',

          // Input field styling
          formFieldInput: 'border border-gray-400 focus:border-black focus:ring-1 focus:ring-black rounded-sm',
          formFieldLabel: 'text-gray-700', // Label text color

          // Link styling (e.g., "Already have an account? Sign In")
          footerActionLink: 'text-black hover:underline',
          // Header titles and subtitles
          headerTitle: 'text-black text-2xl font-bold',
          headerSubtitle: 'text-gray-600',

          // "Or continue with" divider
          dividerLine: 'bg-gray-400',
          dividerText: 'text-gray-600',

          // Error messages
          formMessage: 'text-red-600',
          // Other elements you might want to adjust
          // root: '',
          // button: '',
          // icon: '',
          // etc. (Inspect the browser for more specific Clerk class names if needed)
        },
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
